CREATE TABLE users (
 id VARCHAR (255) PRIMARY KEY UNIQUE NOT NULL,
 email VARCHAR (255) UNIQUE NOT NULL,
 username VARCHAR (255) UNIQUE NOT NULL,
 password VARCHAR (255) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE bots (
 id VARCHAR (255) PRIMARY KEY UNIQUE NOT NULL,
 number VARCHAR (255) UNIQUE NOT NULL,
 user_id VARCHAR (255) NOT NULL REFERENCES users(id),
 token VARCHAR (255) NOT NULL,
 is_verified BOOLEAN DEFAULT FALSE NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE sessionstore (
  bot_id VARCHAR (255) PRIMARY KEY UNIQUE NOT NULL REFERENCES bots(id),
  data BYTEA,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
